# Site settings
title: Jonas Chapuis Home Page # site title
description: >- # site description
  Tech blog and resume
lang: en-US # default lang
timezone: Europe/Zurich # set your timezone
image: assets/img/ogp.png # This image used for Open Graph more info https://ogp.me/
repo: https://github.com/jchapuis/website # site repo [optional]
mode: light # default theme "dark" | "light"

# Profile settings
author:
  name: Jonas Chapuis 
  bio: Software engineer & Scala enthusiast
  username: jchapuis # general username
  github: jchapuis # github username
  twitter: JonasChapuis # twitter username
  avatar: /assets/img/avatar.jpg # change with your own avatar

# URL settings
url: https://jchapuis.github.io
baseurl: /website/
permalink: /:year/:month/:title/
google_analytics: # leave it blank if not wish
fb_appid:

# Collection setting
collections:
  posts:
    output: true

collections:
  - medium_posts

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge


# Default front matter
defaults:
  - scope:
      path: ""
    values:
      layout: post
      comments: false

# Jekyll Compose default front matter
jekyll_compose:
  post_default_front_matter:
    modified:
    tags: []
    description:
  draft_default_front_matter:
    modified:
    tags: []
    description:

# Homepage limit posts
number_of_posts: 10

toc:
  min_level: 1
  max_level: 3

# Build settings
# theme: klise
sass:
  style: compressed

include:
  - _redirects
  - .htaccess

exclude:
  - vendor
  - CNAME
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - CHANGELOG.md
  - README.md
  - node_modules
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - lighthouse.png
  - klise-*.gem
  - klise.gemspec

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-toc
